-- Conformed submission-level table. One row per SurveyCTO submission (duplicates kept, ranked).

CREATE TABLE IF NOT EXISTS silver.survey_submissions (
    survey_cycle                   text        NOT NULL,
    cycle_order                    smallint    NOT NULL,
    submission_key                 text        NOT NULL,
    instance_id                    text,
    household_id                   text,
    household_key                  text,
    household_id_confirmed         boolean,
    submission_ts                  timestamp,
    submission_date                date,
    start_ts                       timestamp,
    end_ts                         timestamp,
    form_version                   text,
    duration_sec                   double precision,
    duration_min                   numeric(10, 2),
    surveyor                       text,
    district_code                  smallint,
    district_code_label            text,
    district_preload               text,
    district_name                  text,
    district_source                text,
    district_form_conflict         boolean,
    subcounty                      text,
    parish                         text,
    village                        text,
    cluster                        text,
    interview_status_code          smallint,
    interview_status_code_label    text,
    track_status                   text,
    consent_participate            smallint,
    consent_followup               smallint,
    refusal_reason_code            smallint,
    refusal_reason_code_label      text,
    respondent_type_code           smallint,
    respondent_type_code_label     text,
    respondent_sex_code            smallint,
    respondent_sex_code_label      text,
    hhh_sex_code                   smallint,
    hhh_sex_code_label             text,
    hhh_age                        smallint,
    hhh_marital_status_code        smallint,
    hhh_marital_status_code_label  text,
    hhh_education_code             smallint,
    hhh_education_code_label       text,
    hh_size                        smallint,
    gps_latitude                   double precision,
    gps_longitude                  double precision,
    gps_accuracy                   double precision,
    has_valid_gps                  boolean     NOT NULL,
    income_consumption_usd_day_aeq double precision,
    household_submission_count     smallint    NOT NULL,
    dedup_rank                     smallint    NOT NULL,
    is_latest                      boolean     NOT NULL,
    bronze_ingest_id               text        NOT NULL,
    bronze_row_hash                text        NOT NULL,
    source_file                    text        NOT NULL,
    ingested_at                    timestamp   NOT NULL  -- UTC
);

-- Uniqueness of (survey_cycle, submission_key) is asserted by a data test rather than a
-- constraint, so a bad export is reported instead of aborting the load.
CREATE INDEX IF NOT EXISTS ix_silver_submission ON silver.survey_submissions (survey_cycle, submission_key);
CREATE INDEX IF NOT EXISTS ix_silver_household ON silver.survey_submissions (household_key, survey_cycle);
